version: '3.8'

services:
  reverse-proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mspr-kafe-gateway
    restart: unless-stopped
    ports:
      - "32769:32769"
    labels:
      - "coolify.managed=true"
      - "coolify.port=32769"
      - "coolify.name=mspr-kafe-gateway"
    environment:
      - PORT=32769
    networks:
      - mspr-network

networks:
  mspr-network:
    driver: bridge
